### ISSUE TITLE
TonimatasDEV update log #1

### ISSUE THREAD

**Issue by danilppzz** [danilppzz/PotLeaves#2]
- [x] Create storage box inventory
- [x] Fix plant place ( Only in the floor )
- [x] Fix hit box ( Wooden Box )
- [x] Add all the team in mod info
- [x] Fix incorrect recipes
- [x] Fix incorrect blockstates
- [x] Fix fabric startup crash
- [x] Fix tabs

**Comment by TonimatasDEV** [comment]
Fixed
