### ISSUE TITLE
how to craft the pods?

### ISSUE THREAD

**Issue by toben1997** [danilppzz/PotLeaves#5]
I have installed the mod, and i tested the pods in creative i like them a lot now i want to put the mod in my survival world, but i could not finde a crafting recipe

**Comment by danilppzz** [comment]
The recipes are set, the only thing is that we have not yet set the compatibility with the JEI & REI mod, which I think is what you are looking for. I will try to add compatibility as soon as possible, stay tuned for new versions :)

In this link u have the RECIPES in  json files https://github.com/danilppzz/PotLeaves/tree/master/common/src/main/resources/data/potleaves/recipes

**Comment by danilppzz** [comment]
- [ ] JEI & REI Integration

**Comment by toben1997** [comment]
thanks for the info but somhow they are not workling
![Screenshot 2024-04-26 174618](https://github.com/danilppzz/PotLeaves/assets/23506168/d2eb5915-0b07-4961-9713-4966fc0843a0)
![Screenshot 2024-04-26 174634](https://github.com/danilppzz/PotLeaves/assets/23506168/a0a59d07-7b73-4a9a-b6ea-bf2366ea6f66)

**Comment by danilppzz** [comment]
sorry to heard that i'll check it

**Comment by toben1997** [comment]
do you have a new discord, i saw your old one got hackt, maby i can yoin and help finding the problem

**Comment by danilppzz** [comment]
https://discord.gg/vdfdAXJGGb
